#!/usr/bin/env bash
set -euo pipefail

#
# Setup Local Environment Files for Parlae
# This script creates .env.local with correct configuration from config.sh
#

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "🚀 Setting up local environment for Parlae..."
echo ""

# Source the main config file
CONFIG_FILE="../config.sh"
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo -e "${RED}ERROR: config.sh not found at $CONFIG_FILE${NC}"
  echo "Please make sure you're running this from the dentia/ directory"
  exit 1
fi

source "$CONFIG_FILE"

echo -e "${GREEN}✓${NC} Loaded configuration from config.sh"
echo "  Project: $PROJECT_NAME"
echo "  Domain: $APP_DOMAIN"
echo ""

# Validate required GHL credentials
if [[ -z "$GHL_API_KEY" ]] || [[ -z "$GHL_LOCATION_ID" ]]; then
  echo -e "${RED}ERROR: GHL credentials not configured in config.sh${NC}"
  echo "Please add GHL_API_KEY and GHL_LOCATION_ID to your config.sh"
  exit 1
fi

echo -e "${GREEN}✓${NC} GHL credentials found"
echo ""

# Create apps/frontend/.env.local
ENV_LOCAL_FILE="apps/frontend/.env.local"
echo "📝 Creating $ENV_LOCAL_FILE..."

cat > "$ENV_LOCAL_FILE" << EOF
# Parlae Local Development Environment
# Auto-generated by setup-local-env.sh
# Generated: $(date)

#=============================================================================
# APPLICATION
#=============================================================================
NODE_ENV=development
APP_BASE_URL=http://localhost:3000
NEXT_PUBLIC_APP_BASE_URL=http://localhost:3000

#=============================================================================
# AUTHENTICATION (NextAuth + Cognito)
#=============================================================================
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# For local dev, you can use Cognito or credentials
ENABLE_CREDENTIALS_SIGNIN=true

# Cognito (if using AWS Cognito locally)
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID:-placeholder-for-local-dev}
COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET:-placeholder-for-local-dev}
COGNITO_ISSUER=https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID:-us-east-2_PLACEHOLDER}

#=============================================================================
# DATABASE
#=============================================================================
# Local PostgreSQL from docker-compose
DATABASE_URL=postgresql://dentia:dentia@localhost:5433/dentia

#=============================================================================
# BACKEND API
#=============================================================================
BACKEND_URL=http://localhost:4001
BACKEND_API_URL=http://localhost:4001

#=============================================================================
# AWS S3 (LocalStack for local dev)
#=============================================================================
AWS_REGION=us-east-1
S3_BUCKET_NAME=${PROJECT_NAME}-local-bucket
S3_PUBLIC_BASE_URL=http://localhost:4567/${PROJECT_NAME}-local-bucket
NEXT_PUBLIC_S3_PUBLIC_BASE_URL=http://localhost:4567/${PROJECT_NAME}-local-bucket

# LocalStack endpoint
AWS_ENDPOINT_URL=http://localhost:4567

#=============================================================================
# GOHIGHLEVEL (GHL) INTEGRATION - PRODUCTION CREDENTIALS
#=============================================================================
# Server-side (API calls)
GHL_API_KEY=${GHL_API_KEY}
GHL_LOCATION_ID=${GHL_LOCATION_ID}

# Client-side (widgets and embeds)
NEXT_PUBLIC_GHL_WIDGET_ID=${GHL_WIDGET_ID}
NEXT_PUBLIC_GHL_LOCATION_ID=${GHL_LOCATION_ID}
NEXT_PUBLIC_GHL_CALENDAR_ID=${GHL_CALENDAR_ID}

#=============================================================================
# DISCOURSE SSO (if using forum)
#=============================================================================
DISCOURSE_SSO_SECRET=${DISCOURSE_SSO_SECRET}
DISCOURSE_CONNECT_URL=https://${HUB_DOMAIN:-hub.parlae.ca}

#=============================================================================
# STRIPE (Optional - for billing)
#=============================================================================
# STRIPE_PUBLISHABLE_KEY=pk_test_...
# STRIPE_SECRET_KEY=sk_test_...
# STRIPE_WEBHOOK_SECRET=whsec_...

#=============================================================================
# EMAIL (Optional - for local testing)
#=============================================================================
# SMTP_ADDRESS=${SMTP_ADDRESS}
# SMTP_PORT=${SMTP_PORT}
# SMTP_USERNAME=${SMTP_USERNAME}
# SMTP_PASSWORD=${SMTP_PASSWORD}

EOF

echo -e "${GREEN}✓${NC} Created $ENV_LOCAL_FILE"
echo ""

# Create root .env for docker-compose
ROOT_ENV_FILE=".env"
echo "📝 Creating $ROOT_ENV_FILE (for docker-compose)..."

cat > "$ROOT_ENV_FILE" << EOF
# Parlae Docker Compose Environment
# Auto-generated by setup-local-env.sh
# Generated: $(date)

# Project
PROJECT_NAME=${PROJECT_NAME}

# NextAuth
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXT_PUBLIC_NEXTAUTH_URL=http://localhost:3009

# Cognito (optional for local)
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID:-placeholder}
COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET:-placeholder}
COGNITO_ISSUER=https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID:-us-east-2_PLACEHOLDER}

# Credentials signin for local dev
ENABLE_CREDENTIALS_SIGNIN=true

# GoHighLevel Integration
GHL_API_KEY=${GHL_API_KEY}
GHL_LOCATION_ID=${GHL_LOCATION_ID}
NEXT_PUBLIC_GHL_WIDGET_ID=${GHL_WIDGET_ID}
NEXT_PUBLIC_GHL_LOCATION_ID=${GHL_LOCATION_ID}
NEXT_PUBLIC_GHL_CALENDAR_ID=${GHL_CALENDAR_ID}

# Discourse SSO
DISCOURSE_SSO_SECRET=${DISCOURSE_SSO_SECRET}

EOF

echo -e "${GREEN}✓${NC} Created $ROOT_ENV_FILE"
echo ""

# Create backend .env if needed
BACKEND_ENV_FILE="apps/backend/.env.local"
echo "📝 Creating $BACKEND_ENV_FILE..."

cat > "$BACKEND_ENV_FILE" << EOF
# Parlae Backend Local Development
# Auto-generated by setup-local-env.sh
# Generated: $(date)

NODE_ENV=development

# Database
DATABASE_URL=postgresql://dentia:dentia@localhost:5433/dentia

# AWS
AWS_REGION=us-east-1
S3_BUCKET_NAME=${PROJECT_NAME}-local-bucket
S3_PUBLIC_BASE_URL=http://localhost:4567/${PROJECT_NAME}-local-bucket

# LocalStack
AWS_ENDPOINT_URL=http://localhost:4567

# Cognito
COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID:-us-east-2_PLACEHOLDER}
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID:-placeholder}
COGNITO_ISSUER=https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID:-us-east-2_PLACEHOLDER}

# GoHighLevel
GHL_API_KEY=${GHL_API_KEY}
GHL_LOCATION_ID=${GHL_LOCATION_ID}

EOF

echo -e "${GREEN}✓${NC} Created $BACKEND_ENV_FILE"
echo ""

echo -e "${GREEN}✅ Local environment setup complete!${NC}"
echo ""
echo "📋 Summary:"
echo "  ✓ Frontend environment: $ENV_LOCAL_FILE"
echo "  ✓ Docker environment: $ROOT_ENV_FILE"
echo "  ✓ Backend environment: $BACKEND_ENV_FILE"
echo "  ✓ GHL Integration: Enabled"
echo "  ✓ Project: $PROJECT_NAME"
echo ""
echo "🚀 Next steps:"
echo "  1. Start development: ./dev.sh"
echo "  2. Test GHL integration at http://localhost:3000"
echo "  3. Register a test user to verify GHL contact sync"
echo ""


