import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { StructuredLogger } from '../../common/structured-logger';
import type {
  OutboundCampaign,
  CampaignContact,
  OutboundCallType,
  OutboundChannel,
  OutboundCampaignStatus,
} from '@kit/prisma';
import { Prisma } from '@kit/prisma';

export interface CreateCampaignInput {
  accountId: string;
  name: string;
  callType: OutboundCallType;
  channel?: OutboundChannel;
  isAutoGenerated?: boolean;
  scheduledStartAt?: Date;
  scheduledEndAt?: Date;
  callingWindowStart?: string;
  callingWindowEnd?: string;
  timezone?: string;
  maxConcurrent?: number;
  maxAttemptsPerContact?: number;
  retellAgentId?: string;
  dynamicVariables?: Record<string, unknown>;
  createdBy?: string;
}

export interface CreateContactInput {
  patientId?: string;
  patientName: string;
  phoneNumber: string;
  email?: string;
  callContext?: Record<string, unknown>;
}

@Injectable()
export class OutboundCampaignService {
  private readonly logger = new StructuredLogger(OutboundCampaignService.name);

  constructor(private readonly prisma: PrismaService) {}

  async createCampaign(input: CreateCampaignInput): Promise<OutboundCampaign> {
    this.logger.log({
      accountId: input.accountId,
      callType: input.callType,
      channel: input.channel,
      isAutoGenerated: input.isAutoGenerated,
      msg: 'Creating outbound campaign',
    });

    return this.prisma.outboundCampaign.create({
      data: {
        accountId: input.accountId,
        name: input.name,
        callType: input.callType,
        channel: input.channel || 'PHONE',
        status: input.scheduledStartAt ? 'SCHEDULED' : 'DRAFT',
        isAutoGenerated: input.isAutoGenerated || false,
        scheduledStartAt: input.scheduledStartAt,
        scheduledEndAt: input.scheduledEndAt,
        callingWindowStart: input.callingWindowStart,
        callingWindowEnd: input.callingWindowEnd,
        timezone: input.timezone || 'America/New_York',
        maxConcurrent: input.maxConcurrent || 1,
        maxAttemptsPerContact: input.maxAttemptsPerContact || 3,
        retellAgentId: input.retellAgentId,
        dynamicVariables: (input.dynamicVariables as Prisma.InputJsonValue) || undefined,
        createdBy: input.createdBy,
      },
    });
  }

  async addContacts(
    campaignId: string,
    contacts: CreateContactInput[],
  ): Promise<{ added: number; skipped: number }> {
    let added = 0;
    let skipped = 0;

    for (const contact of contacts) {
      try {
        await this.prisma.campaignContact.create({
          data: {
            campaignId,
            patientId: contact.patientId,
            patientName: contact.patientName,
            phoneNumber: contact.phoneNumber,
            email: contact.email,
            callContext: (contact.callContext as Prisma.InputJsonValue) || undefined,
          },
        });
        added++;
      } catch (err: any) {
        if (err.code === 'P2002') {
          skipped++;
        } else {
          throw err;
        }
      }
    }

    await this.prisma.outboundCampaign.update({
      where: { id: campaignId },
      data: { totalContacts: { increment: added } },
    });

    this.logger.log({
      campaignId,
      added,
      skipped,
      msg: 'Added contacts to campaign',
    });

    return { added, skipped };
  }

  async getCampaign(id: string): Promise<OutboundCampaign | null> {
    return this.prisma.outboundCampaign.findUnique({ where: { id } });
  }

  async listCampaigns(
    accountId: string,
    filters?: {
      status?: OutboundCampaignStatus;
      callType?: OutboundCallType;
      isAutoGenerated?: boolean;
    },
  ): Promise<OutboundCampaign[]> {
    return this.prisma.outboundCampaign.findMany({
      where: {
        accountId,
        ...(filters?.status ? { status: filters.status } : {}),
        ...(filters?.callType ? { callType: filters.callType } : {}),
        ...(filters?.isAutoGenerated !== undefined
          ? { isAutoGenerated: filters.isAutoGenerated }
          : {}),
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  async updateCampaignStatus(
    id: string,
    status: OutboundCampaignStatus,
  ): Promise<OutboundCampaign> {
    this.logger.log({ campaignId: id, status, msg: 'Updating campaign status' });
    return this.prisma.outboundCampaign.update({
      where: { id },
      data: { status },
    });
  }

  async getContacts(
    campaignId: string,
    filters?: { status?: string },
  ): Promise<CampaignContact[]> {
    return this.prisma.campaignContact.findMany({
      where: {
        campaignId,
        ...(filters?.status ? { status: filters.status as any } : {}),
      },
      orderBy: { createdAt: 'asc' },
    });
  }

  async getQueuedContacts(
    campaignId: string,
    limit: number,
  ): Promise<CampaignContact[]> {
    return this.prisma.campaignContact.findMany({
      where: { campaignId, status: 'QUEUED' },
      orderBy: { createdAt: 'asc' },
      take: limit,
    });
  }

  async updateContactStatus(
    contactId: string,
    data: Partial<
      Pick<
        CampaignContact,
        | 'status'
        | 'attempts'
        | 'lastAttemptAt'
        | 'completedAt'
        | 'retellCallId'
        | 'outcome'
        | 'callDurationSec'
        | 'summary'
        | 'sentiment'
        | 'analysisData'
      >
    >,
  ): Promise<CampaignContact> {
    const updateData = { ...data } as Record<string, unknown>;
    if (data.analysisData === null) {
      updateData.analysisData = Prisma.JsonNull;
    }
    return this.prisma.campaignContact.update({
      where: { id: contactId },
      data: updateData as Prisma.CampaignContactUncheckedUpdateInput,
    });
  }

  async incrementCampaignStats(
    campaignId: string,
    completed: boolean,
    successful: boolean,
  ): Promise<void> {
    const data: Record<string, unknown> = {};
    if (completed) data.completedCount = { increment: 1 };
    if (successful) data.successfulCount = { increment: 1 };

    if (Object.keys(data).length > 0) {
      await this.prisma.outboundCampaign.update({
        where: { id: campaignId },
        data,
      });
    }
  }

  async checkAndCompleteCampaign(campaignId: string): Promise<void> {
    const campaign = await this.prisma.outboundCampaign.findUnique({
      where: { id: campaignId },
    });
    if (!campaign || campaign.status !== 'ACTIVE') return;

    const remaining = await this.prisma.campaignContact.count({
      where: {
        campaignId,
        status: { in: ['QUEUED', 'DIALING', 'IN_PROGRESS'] },
      },
    });

    if (remaining === 0) {
      await this.updateCampaignStatus(campaignId, 'COMPLETED');
      this.logger.log({ campaignId, msg: 'Campaign completed — all contacts processed' });
    }
  }
}
