import { Test, TestingModule } from '@nestjs/testing';
import { OutboundCampaignService } from './outbound-campaign.service';
import { PrismaService } from '../../prisma/prisma.service';
import { createMockPrismaService } from '../../test/mocks/prisma.mock';

describe('OutboundCampaignService', () => {
  let service: OutboundCampaignService;
  let prisma: any;

  beforeEach(async () => {
    const mockPrisma = createMockPrismaService();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        OutboundCampaignService,
        { provide: PrismaService, useValue: mockPrisma },
      ],
    }).compile();

    service = module.get<OutboundCampaignService>(OutboundCampaignService);
    prisma = module.get(PrismaService);
  });

  afterEach(() => jest.clearAllMocks());

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('createCampaign', () => {
    it('creates a DRAFT campaign when no scheduledStartAt', async () => {
      const created = { id: 'camp-1', status: 'DRAFT' };
      prisma.outboundCampaign.create.mockResolvedValue(created);

      const result = await service.createCampaign({
        accountId: 'acc-1',
        name: 'Test Campaign',
        callType: 'RECALL' as any,
      });

      expect(result).toEqual(created);
      const call = prisma.outboundCampaign.create.mock.calls[0][0];
      expect(call.data.status).toBe('DRAFT');
      expect(call.data.channel).toBe('PHONE');
      expect(call.data.maxConcurrent).toBe(1);
      expect(call.data.maxAttemptsPerContact).toBe(3);
    });

    it('creates a SCHEDULED campaign when scheduledStartAt is provided', async () => {
      const startAt = new Date();
      prisma.outboundCampaign.create.mockResolvedValue({ id: 'camp-1', status: 'SCHEDULED' });

      await service.createCampaign({
        accountId: 'acc-1',
        name: 'Scheduled Campaign',
        callType: 'REMINDER' as any,
        scheduledStartAt: startAt,
      });

      const call = prisma.outboundCampaign.create.mock.calls[0][0];
      expect(call.data.status).toBe('SCHEDULED');
      expect(call.data.scheduledStartAt).toBe(startAt);
    });

    it('passes all optional fields', async () => {
      prisma.outboundCampaign.create.mockResolvedValue({ id: 'camp-1' });

      await service.createCampaign({
        accountId: 'acc-1',
        name: 'Full Config',
        callType: 'NOSHOW' as any,
        channel: 'SMS' as any,
        isAutoGenerated: true,
        timezone: 'America/Chicago',
        maxConcurrent: 5,
        maxAttemptsPerContact: 2,
        retellAgentId: 'agent-1',
        createdBy: 'admin',
      });

      const call = prisma.outboundCampaign.create.mock.calls[0][0];
      expect(call.data.channel).toBe('SMS');
      expect(call.data.isAutoGenerated).toBe(true);
      expect(call.data.maxConcurrent).toBe(5);
      expect(call.data.retellAgentId).toBe('agent-1');
      expect(call.data.createdBy).toBe('admin');
    });
  });

  describe('addContacts', () => {
    it('adds contacts and returns count', async () => {
      prisma.campaignContact.create.mockResolvedValue({});
      prisma.outboundCampaign.update.mockResolvedValue({});

      const result = await service.addContacts('camp-1', [
        { patientId: 'p1', phoneNumber: '+11234567890' },
        { patientId: 'p2', phoneNumber: '+10987654321' },
      ]);

      expect(result).toEqual({ added: 2, skipped: 0 });
      expect(prisma.campaignContact.create).toHaveBeenCalledTimes(2);
      expect(prisma.outboundCampaign.update).toHaveBeenCalledWith({
        where: { id: 'camp-1' },
        data: { totalContacts: { increment: 2 } },
      });
    });

    it('skips duplicate contacts (P2002 error)', async () => {
      const dupeError = Object.assign(new Error('Duplicate'), { code: 'P2002' });
      prisma.campaignContact.create
        .mockResolvedValueOnce({})
        .mockRejectedValueOnce(dupeError);
      prisma.outboundCampaign.update.mockResolvedValue({});

      const result = await service.addContacts('camp-1', [
        { patientId: 'p1' },
        { patientId: 'p1' },
      ]);

      expect(result).toEqual({ added: 1, skipped: 1 });
    });

    it('throws non-duplicate errors', async () => {
      prisma.campaignContact.create.mockRejectedValue(new Error('DB down'));

      await expect(
        service.addContacts('camp-1', [{ patientId: 'p1' }]),
      ).rejects.toThrow('DB down');
    });
  });

  describe('getCampaign', () => {
    it('returns campaign by id', async () => {
      const campaign = { id: 'camp-1', accountId: 'acc-1' };
      prisma.outboundCampaign.findUnique.mockResolvedValue(campaign);

      const result = await service.getCampaign('camp-1');
      expect(result).toEqual(campaign);
    });

    it('returns null when not found', async () => {
      prisma.outboundCampaign.findUnique.mockResolvedValue(null);
      const result = await service.getCampaign('missing');
      expect(result).toBeNull();
    });
  });

  describe('listCampaigns', () => {
    it('lists campaigns for account with no filters', async () => {
      prisma.outboundCampaign.findMany.mockResolvedValue([]);
      await service.listCampaigns('acc-1');

      expect(prisma.outboundCampaign.findMany).toHaveBeenCalledWith({
        where: { accountId: 'acc-1' },
        orderBy: { createdAt: 'desc' },
      });
    });

    it('applies status filter', async () => {
      prisma.outboundCampaign.findMany.mockResolvedValue([]);
      await service.listCampaigns('acc-1', { status: 'ACTIVE' as any });

      const call = prisma.outboundCampaign.findMany.mock.calls[0][0];
      expect(call.where.status).toBe('ACTIVE');
    });

    it('applies callType and isAutoGenerated filters', async () => {
      prisma.outboundCampaign.findMany.mockResolvedValue([]);
      await service.listCampaigns('acc-1', {
        callType: 'RECALL' as any,
        isAutoGenerated: true,
      });

      const call = prisma.outboundCampaign.findMany.mock.calls[0][0];
      expect(call.where.callType).toBe('RECALL');
      expect(call.where.isAutoGenerated).toBe(true);
    });
  });

  describe('updateCampaignStatus', () => {
    it('updates campaign status', async () => {
      prisma.outboundCampaign.update.mockResolvedValue({ id: 'camp-1', status: 'ACTIVE' });
      const result = await service.updateCampaignStatus('camp-1', 'ACTIVE' as any);
      expect(result.status).toBe('ACTIVE');
      expect(prisma.outboundCampaign.update).toHaveBeenCalledWith({
        where: { id: 'camp-1' },
        data: { status: 'ACTIVE' },
      });
    });
  });

  describe('approveCampaign', () => {
    it('approves a DRAFT campaign to ACTIVE', async () => {
      prisma.outboundCampaign.findUnique.mockResolvedValue({ id: 'camp-1', status: 'DRAFT' });
      prisma.outboundCampaign.update.mockResolvedValue({ id: 'camp-1', status: 'ACTIVE' });

      const result = await service.approveCampaign('camp-1');
      expect(result.status).toBe('ACTIVE');
      expect(prisma.outboundCampaign.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 'camp-1' },
          data: expect.objectContaining({ status: 'ACTIVE' }),
        }),
      );
    });

    it('throws when campaign not found', async () => {
      prisma.outboundCampaign.findUnique.mockResolvedValue(null);
      await expect(service.approveCampaign('missing')).rejects.toThrow('Campaign not found');
    });

    it('throws when campaign is not DRAFT', async () => {
      prisma.outboundCampaign.findUnique.mockResolvedValue({ id: 'camp-1', status: 'ACTIVE' });
      await expect(service.approveCampaign('camp-1')).rejects.toThrow('Cannot approve campaign with status ACTIVE');
    });
  });

  describe('approveAllDraftCampaigns', () => {
    it('bulk approves all DRAFT campaigns for account', async () => {
      prisma.outboundCampaign.updateMany.mockResolvedValue({ count: 3 });
      const result = await service.approveAllDraftCampaigns('acc-1');

      expect(result).toEqual({ approved: 3 });
      expect(prisma.outboundCampaign.updateMany).toHaveBeenCalledWith({
        where: { accountId: 'acc-1', status: 'DRAFT' },
        data: expect.objectContaining({ status: 'ACTIVE' }),
      });
    });

    it('returns 0 when no DRAFT campaigns', async () => {
      prisma.outboundCampaign.updateMany.mockResolvedValue({ count: 0 });
      const result = await service.approveAllDraftCampaigns('acc-1');
      expect(result).toEqual({ approved: 0 });
    });
  });

  describe('getContacts', () => {
    it('returns contacts for campaign', async () => {
      const contacts = [{ id: 'c1' }, { id: 'c2' }];
      prisma.campaignContact.findMany.mockResolvedValue(contacts);

      const result = await service.getContacts('camp-1');
      expect(result).toEqual(contacts);
    });

    it('filters by status', async () => {
      prisma.campaignContact.findMany.mockResolvedValue([]);
      await service.getContacts('camp-1', { status: 'QUEUED' });

      const call = prisma.campaignContact.findMany.mock.calls[0][0];
      expect(call.where.status).toBe('QUEUED');
    });
  });

  describe('getQueuedContacts', () => {
    it('returns queued contacts with limit', async () => {
      prisma.campaignContact.findMany.mockResolvedValue([{ id: 'c1' }]);
      const result = await service.getQueuedContacts('camp-1', 5);

      expect(result).toHaveLength(1);
      expect(prisma.campaignContact.findMany).toHaveBeenCalledWith({
        where: { campaignId: 'camp-1', status: 'QUEUED' },
        orderBy: { createdAt: 'asc' },
        take: 5,
      });
    });
  });

  describe('updateContactStatus', () => {
    it('updates contact fields', async () => {
      prisma.campaignContact.update.mockResolvedValue({ id: 'c1', status: 'COMPLETED' });
      const result = await service.updateContactStatus('c1', {
        status: 'COMPLETED' as any,
        outcome: 'answered',
      });

      expect(result.status).toBe('COMPLETED');
    });

    it('handles null analysisData with Prisma.JsonNull', async () => {
      prisma.campaignContact.update.mockResolvedValue({ id: 'c1' });
      await service.updateContactStatus('c1', { analysisData: null as any });

      const call = prisma.campaignContact.update.mock.calls[0][0];
      expect(call.data.analysisData).toBeDefined();
    });
  });

  describe('incrementCampaignStats', () => {
    it('increments completedCount when completed', async () => {
      prisma.outboundCampaign.update.mockResolvedValue({});
      await service.incrementCampaignStats('camp-1', true, false);

      expect(prisma.outboundCampaign.update).toHaveBeenCalledWith({
        where: { id: 'camp-1' },
        data: { completedCount: { increment: 1 } },
      });
    });

    it('increments both counts when completed and successful', async () => {
      prisma.outboundCampaign.update.mockResolvedValue({});
      await service.incrementCampaignStats('camp-1', true, true);

      const call = prisma.outboundCampaign.update.mock.calls[0][0];
      expect(call.data.completedCount).toEqual({ increment: 1 });
      expect(call.data.successfulCount).toEqual({ increment: 1 });
    });

    it('does not update when neither completed nor successful', async () => {
      await service.incrementCampaignStats('camp-1', false, false);
      expect(prisma.outboundCampaign.update).not.toHaveBeenCalled();
    });
  });

  describe('checkAndCompleteCampaign', () => {
    it('marks campaign as COMPLETED when no remaining contacts', async () => {
      prisma.outboundCampaign.findUnique.mockResolvedValue({ id: 'camp-1', status: 'ACTIVE' });
      prisma.campaignContact.count.mockResolvedValue(0);
      prisma.outboundCampaign.update.mockResolvedValue({});

      await service.checkAndCompleteCampaign('camp-1');
      expect(prisma.outboundCampaign.update).toHaveBeenCalledWith({
        where: { id: 'camp-1' },
        data: { status: 'COMPLETED' },
      });
    });

    it('does not complete when remaining contacts exist', async () => {
      prisma.outboundCampaign.findUnique.mockResolvedValue({ id: 'camp-1', status: 'ACTIVE' });
      prisma.campaignContact.count.mockResolvedValue(3);

      await service.checkAndCompleteCampaign('camp-1');
      expect(prisma.outboundCampaign.update).not.toHaveBeenCalled();
    });

    it('returns early when campaign not found', async () => {
      prisma.outboundCampaign.findUnique.mockResolvedValue(null);
      await service.checkAndCompleteCampaign('missing');
      expect(prisma.campaignContact.count).not.toHaveBeenCalled();
    });

    it('returns early when campaign is not ACTIVE', async () => {
      prisma.outboundCampaign.findUnique.mockResolvedValue({ id: 'camp-1', status: 'COMPLETED' });
      await service.checkAndCompleteCampaign('camp-1');
      expect(prisma.campaignContact.count).not.toHaveBeenCalled();
    });
  });
});
