'use client';

import { useState, useTransition, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { useRouter } from 'next/navigation';
import { Card, CardContent } from '@kit/ui/card';
import { Badge } from '@kit/ui/badge';
import { Button } from '@kit/ui/button';
import { Checkbox } from '@kit/ui/checkbox';
import { toast } from '@kit/ui/sonner';
import { useCsrfToken } from '@kit/shared/hooks/use-csrf-token';
import {
  AlertDialog,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
} from '@kit/ui/alert-dialog';
import {
  PhoneOutgoing, MessageSquare, Mail, Ban, ChevronDown, ChevronUp,
  Pause, Play, XCircle, Users, CheckCircle2, Clock, Phone,
  AlertCircle, Loader2, Trash2, ShieldBan, ChevronLeft, ChevronRight,
} from 'lucide-react';

const CHANNEL_ICONS: Record<string, typeof PhoneOutgoing> = {
  NONE: Ban,
  PHONE: PhoneOutgoing,
  SMS: MessageSquare,
  EMAIL: Mail,
};

interface CampaignContact {
  id: string;
  patientId: string;
  phoneNumber: string | null;
  callContext?: Record<string, unknown> | null;
  status: string;
  outcome: string | null;
  attempts: number;
  lastAttemptAt: string | null;
}

interface ContactsPagination {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

interface CampaignDetail {
  contacts: CampaignContact[];
  contactsPagination: ContactsPagination;
  statusBreakdown: Record<string, number>;
  outcomeBreakdown: Record<string, number>;
}

interface Campaign {
  id: string;
  name: string;
  callType: string;
  channel: string;
  status: string;
  totalContacts: number;
  completedCount: number;
  successfulCount: number;
  isAutoGenerated: boolean;
  createdAt: string;
}

interface CampaignCardProps {
  campaign: Campaign;
  callTypeLabel: string;
  channelLabel: string;
  onDeleted?: () => void;
}

const STATUS_COLORS: Record<string, string> = {
  ACTIVE: 'bg-green-600',
  PAUSED: 'bg-amber-500',
  COMPLETED: 'bg-blue-600',
  DRAFT: 'bg-gray-500',
  SCHEDULED: 'bg-purple-600',
  CANCELLED: 'bg-red-500',
};

const CONTACT_STATUS_ICONS: Record<string, typeof CheckCircle2> = {
  COMPLETED: CheckCircle2,
  IN_PROGRESS: Phone,
  QUEUED: Clock,
  FAILED: AlertCircle,
  SKIPPED: XCircle,
  NO_ANSWER: Phone,
  BUSY: Phone,
  VOICEMAIL: Phone,
  CANCELLED: XCircle,
};

const CONTACT_STATUS_STYLE: Record<string, string> = {
  COMPLETED: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
  IN_PROGRESS: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
  QUEUED: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
  FAILED: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  NO_ANSWER: 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400',
  BUSY: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
  VOICEMAIL: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400',
  SKIPPED: 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-500',
  CANCELLED: 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-500',
};

const OUTCOME_STYLE: Record<string, string> = {
  booked: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
  confirmed: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
  scheduled: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
  interested: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
  callback_requested: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
  voicemail_left: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400',
  declined: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  not_interested: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  no_answer: 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400',
  busy: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
  wrong_number: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
  disconnected: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400',
  admin_aborted: 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-500',
};

function formatLabel(raw: string): string {
  return raw
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const CONTACTS_PER_PAGE = 20;

export function CampaignCard({ campaign, callTypeLabel, channelLabel, onDeleted }: CampaignCardProps) {
  const { t } = useTranslation('common');
  const getCsrfToken = useCsrfToken;
  const router = useRouter();
  const [expanded, setExpanded] = useState(false);
  const [detail, setDetail] = useState<CampaignDetail | null>(null);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [isPending, startTransition] = useTransition();
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [contactActionPending, setContactActionPending] = useState(false);
  const [deletePending, setDeletePending] = useState(false);
  const [patientNames, setPatientNames] = useState<Record<string, string>>({});
  const [contactPage, setContactPage] = useState(1);

  const [currentChannel, setCurrentChannel] = useState(campaign.channel);
  const [currentStatus, setCurrentStatus] = useState(campaign.status);
  const ChannelIcon = CHANNEL_ICONS[currentChannel] || PhoneOutgoing;
  const progress = campaign.totalContacts > 0
    ? Math.round((campaign.completedCount / campaign.totalContacts) * 100)
    : 0;

  const canApprove = currentStatus === 'DRAFT';
  const canPause = currentStatus === 'ACTIVE';
  const canResume = currentStatus === 'PAUSED';
  const canCancel = ['ACTIVE', 'PAUSED', 'SCHEDULED', 'DRAFT'].includes(currentStatus);
  const CHANNEL_ORDER = ['NONE', 'PHONE', 'SMS', 'EMAIL'] as const;
  const CHANNEL_LABELS: Record<string, string> = {
    NONE: t('outbound.channelPrefs.channels.none', 'Off'),
    PHONE: t('outbound.channelPrefs.channels.phone', 'Phone'),
    SMS: t('outbound.channelPrefs.channels.sms', 'SMS'),
    EMAIL: t('outbound.channelPrefs.channels.email', 'Email'),
  };

  const canChangeChannel = !['COMPLETED', 'CANCELLED'].includes(currentStatus);

  const setChannel = async (channel: string) => {
    if (channel === currentChannel) return;
    const prev = currentChannel;
    setCurrentChannel(channel);
    try {
      const res = await fetch(`/api/outbound/campaigns/${campaign.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', 'x-csrf-token': getCsrfToken() },
        body: JSON.stringify({ action: 'setChannel', channel }),
      });
      if (!res.ok) throw new Error();
    } catch {
      setCurrentChannel(prev);
      toast.error(t('outbound.campaign.channelUpdateFailed', 'Failed to update channel'));
    }
  };

  const fetchDetail = useCallback(async (page = 1) => {
    setLoadingDetail(true);
    try {
      const params = new URLSearchParams({
        contactPage: String(page),
        contactLimit: String(CONTACTS_PER_PAGE),
      });
      const res = await fetch(`/api/outbound/campaigns/${campaign.id}?${params}`);
      if (!res.ok) throw new Error('Failed to fetch');
      const data = await res.json();
      setDetail(data);

      const ids = (data.contacts || []).map((c: any) => c.patientId).filter(Boolean);
      if (ids.length > 0) {
        fetch('/api/outbound/patients/resolve', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'x-csrf-token': getCsrfToken() },
          body: JSON.stringify({ patientIds: ids }),
        })
          .then((r) => (r.ok ? r.json() : null))
          .then((d) => { if (d?.names) setPatientNames((prev) => ({ ...prev, ...d.names })); })
          .catch(() => {});
      }
    } catch {
      toast.error('Failed to load campaign details');
    } finally {
      setLoadingDetail(false);
    }
  }, [campaign.id]);

  function handleToggleExpand() {
    const next = !expanded;
    setExpanded(next);
    if (next) {
      setContactPage(1);
      fetchDetail(1);
    }
    if (!next) setSelectedIds(new Set());
  }

  function handleContactPageChange(newPage: number) {
    setContactPage(newPage);
    setSelectedIds(new Set());
    fetchDetail(newPage);
  }

  const STATUS_MAP: Record<string, string> = {
    pause: 'PAUSED',
    resume: 'ACTIVE',
    cancel: 'CANCELLED',
    approve: 'ACTIVE',
  };

  function handleAction(action: 'pause' | 'resume' | 'cancel' | 'approve') {
    startTransition(async () => {
      try {
        const res = await fetch(`/api/outbound/campaigns/${campaign.id}`, {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'x-csrf-token': getCsrfToken(),
          },
          credentials: 'include',
          body: JSON.stringify({ action }),
        });

        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          throw new Error(data.error || `Failed to ${action}`);
        }

        const newStatus = STATUS_MAP[action] ?? currentStatus;
        setCurrentStatus(newStatus);

        const labels: Record<string, string> = {
          pause: t('outbound.campaignActions.paused'),
          resume: t('outbound.campaignActions.resumed'),
          cancel: t('outbound.campaignActions.cancelled'),
          approve: t('outbound.campaignActions.approved', 'Campaign approved'),
        };
        toast.success(labels[action] ?? 'Done');
        setDetail(null);
        router.refresh();
      } catch (err) {
        toast.error(err instanceof Error ? err.message : `Failed to ${action} campaign`);
      }
    });
  }

  const toggleSelect = useCallback((id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const toggleSelectAll = useCallback(() => {
    if (!detail) return;
    setSelectedIds((prev) => {
      if (prev.size === detail.contacts.length) return new Set();
      return new Set(detail.contacts.map((c) => c.id));
    });
  }, [detail]);

  async function handleContactAction(action: 'remove' | 'add_to_dnc', ids?: string[]) {
    const targetIds = ids ?? Array.from(selectedIds);
    if (targetIds.length === 0) return;
    setContactActionPending(true);
    try {
      const res = await fetch(`/api/outbound/campaigns/${campaign.id}/contacts`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-csrf-token': getCsrfToken(),
        },
        credentials: 'include',
        body: JSON.stringify({ action, contactIds: targetIds }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Failed');
      }

      const result = await res.json();
      if (action === 'remove') {
        toast.success(t('outbound.contactActions.removed', { count: result.removed }));
      } else {
        toast.success(t('outbound.contactActions.addedToDnc', { count: result.dncAdded }));
      }

      setSelectedIds(new Set());
      fetchDetail(contactPage);
      router.refresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed');
    } finally {
      setContactActionPending(false);
    }
  }

  async function handleDeleteCampaign() {
    setDeletePending(true);
    try {
      const res = await fetch(`/api/outbound/campaigns/${campaign.id}`, {
        method: 'DELETE',
        headers: { 'x-csrf-token': getCsrfToken() },
        credentials: 'include',
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Failed to delete');
      }
      toast.success(t('outbound.campaignActions.deleted', 'Campaign deleted'));
      onDeleted?.();
      router.refresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to delete campaign');
    } finally {
      setDeletePending(false);
    }
  }

  const canDelete = !['ACTIVE', 'SCHEDULED'].includes(currentStatus);
  const statusColor = STATUS_COLORS[currentStatus] || 'bg-gray-500';
  const allSelected = detail ? selectedIds.size === detail.contacts.length && detail.contacts.length > 0 : false;
  const someSelected = selectedIds.size > 0;
  const cPag = detail?.contactsPagination;

  const cardDim =
    currentStatus === 'CANCELLED'
      ? 'opacity-50'
      : currentStatus === 'COMPLETED'
        ? 'opacity-70'
        : '';

  return (
    <Card className={`${expanded ? 'ring-1 ring-primary/20' : 'transition-shadow'} ${cardDim}`}>
      <CardContent className="pt-0 pb-0">
        <button
          type="button"
          className={`flex items-center justify-between w-full text-left cursor-pointer rounded-lg px-4 py-4 -mx-4 transition-colors group ${
            expanded ? '' : 'hover:bg-muted/50'
          }`}
          onClick={handleToggleExpand}
        >
          <div className="flex items-center gap-3">
            <div className="rounded-full bg-muted p-2">
              <ChannelIcon className="h-4 w-4 text-muted-foreground" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <p className="font-medium text-sm group-hover:text-primary transition-colors">{campaign.name}</p>
                {campaign.isAutoGenerated && (
                  <Badge variant="outline" className="text-xs">
                    {t('outbound.campaign.auto')}
                  </Badge>
                )}
              </div>
              <p className="text-xs text-muted-foreground">
                {callTypeLabel} &middot; {CHANNEL_LABELS[currentChannel] || channelLabel}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-right text-sm">
              <p className="font-medium">{campaign.completedCount}/{campaign.totalContacts}</p>
              <p className="text-xs text-muted-foreground">
                {t('outbound.campaign.percentComplete', { percent: progress })}
              </p>
            </div>
            <div className="w-24">
              <div className="h-2 bg-muted rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full transition-all ${statusColor}`}
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>
            <Badge
              variant={
                currentStatus === 'ACTIVE' ? 'default'
                  : currentStatus === 'COMPLETED' ? 'secondary'
                  : 'outline'
              }
              className={currentStatus === 'ACTIVE' ? 'bg-green-600' : currentStatus === 'PAUSED' ? 'bg-amber-500 text-white border-amber-500' : currentStatus === 'CANCELLED' ? 'bg-red-500 text-white border-red-500' : ''}
            >
              {t(`outbound.campaign.status.${currentStatus.toLowerCase()}`)}
            </Badge>
            <div className={`rounded-full p-1 transition-colors ${expanded ? 'bg-primary/10' : 'group-hover:bg-muted'}`}>
              {expanded ? (
                <ChevronUp className="h-4 w-4 text-primary" />
              ) : (
                <ChevronDown className="h-4 w-4 text-muted-foreground group-hover:text-foreground transition-colors" />
              )}
            </div>
          </div>
        </button>

        {expanded && (
          <div className="mx-4 mb-4 border-t pt-4 space-y-4">
            <div className="flex items-center justify-between">
              <p className="text-xs text-muted-foreground">
                {t('outbound.campaignActions.created')}: {new Date(campaign.createdAt).toLocaleDateString()}
              </p>
              <div className="flex items-center gap-2">
                {canApprove && (
                  <Button
                    size="sm"
                    onClick={() => handleAction('approve')}
                    disabled={isPending}
                    className="bg-green-600 text-white hover:bg-green-700"
                  >
                    <CheckCircle2 className="h-3.5 w-3.5 mr-1.5" />
                    {t('outbound.campaignActions.approve', 'Approve & Start')}
                  </Button>
                )}
                {canPause && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleAction('pause')}
                    disabled={isPending}
                    className="text-amber-600 border-amber-300 hover:bg-amber-50 dark:hover:bg-amber-950/20"
                  >
                    <Pause className="h-3.5 w-3.5 mr-1.5" />
                    {t('outbound.campaignActions.pause')}
                  </Button>
                )}
                {canResume && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleAction('resume')}
                    disabled={isPending}
                    className="text-green-600 border-green-300 hover:bg-green-50 dark:hover:bg-green-950/20"
                  >
                    <Play className="h-3.5 w-3.5 mr-1.5" />
                    {t('outbound.campaignActions.resume')}
                  </Button>
                )}
                {canCancel && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleAction('cancel')}
                    disabled={isPending}
                    className="text-red-600 border-red-300 hover:bg-red-50 dark:hover:bg-red-950/20"
                  >
                    <XCircle className="h-3.5 w-3.5 mr-1.5" />
                    {t('outbound.campaignActions.cancel')}
                  </Button>
                )}
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button
                      size="sm"
                      variant="outline"
                      disabled={!canDelete || deletePending}
                      className="text-red-600 border-red-300 hover:bg-red-50 dark:hover:bg-red-950/20"
                    >
                      {deletePending ? (
                        <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" />
                      ) : (
                        <Trash2 className="h-3.5 w-3.5 mr-1.5" />
                      )}
                      {t('outbound.campaignActions.delete', 'Delete')}
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>
                        {t('outbound.campaignActions.deleteConfirmTitle', 'Delete this campaign?')}
                      </AlertDialogTitle>
                      <AlertDialogDescription>
                        {t(
                          'outbound.campaignActions.deleteConfirmDescription',
                          'This will permanently delete the campaign and all its contact records. This action cannot be undone.',
                        )}
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>{t('common:cancel', 'Cancel')}</AlertDialogCancel>
                      <AlertDialogAction
                        onClick={handleDeleteCampaign}
                        className="bg-red-600 hover:bg-red-700"
                      >
                        {t('outbound.campaignActions.deleteConfirm', 'Delete')}
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </div>
            </div>

            <div className="flex items-center justify-between rounded-lg border p-3">
              <p className="text-sm font-medium">
                {t('outbound.campaign.channelLabel', 'Channel')}
              </p>
              <div className="flex items-center gap-0.5 rounded-lg border bg-muted/40 p-0.5">
                {CHANNEL_ORDER.map((ch) => {
                  const active = currentChannel === ch;
                  const Icon = CHANNEL_ICONS[ch] || PhoneOutgoing;
                  return (
                    <button
                      key={ch}
                      type="button"
                      disabled={!canChangeChannel || isPending}
                      onClick={() => setChannel(ch)}
                      className={`flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium transition-all ${
                        active
                          ? ch === 'NONE'
                            ? 'bg-destructive/15 text-destructive shadow-sm ring-1 ring-destructive/30'
                            : 'bg-primary text-primary-foreground shadow-sm'
                          : 'text-muted-foreground hover:text-foreground hover:bg-muted/60'
                      } ${!canChangeChannel || isPending ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
                    >
                      <Icon className="h-3 w-3" />
                      {CHANNEL_LABELS[ch]}
                    </button>
                  );
                })}
              </div>
            </div>

            {loadingDetail ? (
              <div className="flex items-center justify-center py-6">
                <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
              </div>
            ) : detail ? (
              <>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  <div className="rounded-lg bg-muted/50 p-3 text-center">
                    <Users className="h-4 w-4 mx-auto mb-1 text-muted-foreground" />
                    <p className="text-lg font-semibold">{campaign.totalContacts}</p>
                    <p className="text-xs text-muted-foreground">{t('outbound.campaign.contacts')}</p>
                  </div>
                  <div className="rounded-lg bg-muted/50 p-3 text-center">
                    <CheckCircle2 className="h-4 w-4 mx-auto mb-1 text-green-600" />
                    <p className="text-lg font-semibold">{campaign.completedCount}</p>
                    <p className="text-xs text-muted-foreground">{t('outbound.campaign.completed')}</p>
                  </div>
                  <div className="rounded-lg bg-muted/50 p-3 text-center">
                    <CheckCircle2 className="h-4 w-4 mx-auto mb-1 text-blue-600" />
                    <p className="text-lg font-semibold">{campaign.successfulCount}</p>
                    <p className="text-xs text-muted-foreground">{t('outbound.campaign.successful')}</p>
                  </div>
                  <div className="rounded-lg bg-muted/50 p-3 text-center">
                    <Clock className="h-4 w-4 mx-auto mb-1 text-amber-600" />
                    <p className="text-lg font-semibold">
                      {campaign.totalContacts - campaign.completedCount}
                    </p>
                    <p className="text-xs text-muted-foreground">{t('outbound.campaignActions.remaining')}</p>
                  </div>
                </div>

                {Object.keys(detail.outcomeBreakdown).length > 0 && (
                  <div>
                    <p className="text-sm font-medium mb-2">{t('outbound.campaignActions.outcomes')}</p>
                    <div className="flex flex-wrap gap-2">
                      {Object.entries(detail.outcomeBreakdown).map(([outcome, count]) => (
                        <span
                          key={outcome}
                          className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium ${OUTCOME_STYLE[outcome] || 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400'}`}
                        >
                          {formatLabel(outcome)}
                          <span className="rounded-full bg-black/10 dark:bg-white/10 px-1.5 py-0.5 text-[10px] leading-none font-semibold">
                            {count}
                          </span>
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                {(detail.contacts.length > 0 || (cPag && cPag.total > 0)) && (
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <p className="text-sm font-medium">
                        {t('outbound.campaignActions.recentContacts')} ({cPag?.total ?? detail.contacts.length})
                      </p>
                      {someSelected && (
                        <div className="flex items-center gap-2">
                          <span className="text-xs text-muted-foreground">
                            {t('outbound.contactActions.selected', { count: selectedIds.size })}
                          </span>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleContactAction('remove')}
                            disabled={contactActionPending}
                            className="h-7 text-xs text-red-600 border-red-300 hover:bg-red-50 dark:hover:bg-red-950/20"
                          >
                            {contactActionPending ? (
                              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                            ) : (
                              <Trash2 className="h-3 w-3 mr-1" />
                            )}
                            {t('outbound.contactActions.remove')}
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleContactAction('add_to_dnc')}
                            disabled={contactActionPending}
                            className="h-7 text-xs text-amber-600 border-amber-300 hover:bg-amber-50 dark:hover:bg-amber-950/20"
                          >
                            {contactActionPending ? (
                              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                            ) : (
                              <ShieldBan className="h-3 w-3 mr-1" />
                            )}
                            {t('outbound.contactActions.addToDnc')}
                          </Button>
                        </div>
                      )}
                    </div>
                    <div className="border rounded-lg overflow-hidden">
                      <div className="max-h-80 overflow-y-auto">
                        <table className="w-full text-sm">
                          <thead className="bg-muted/50 sticky top-0">
                            <tr>
                              <th className="w-10 px-3 py-2">
                                <Checkbox
                                  checked={allSelected}
                                  onCheckedChange={toggleSelectAll}
                                  aria-label="Select all"
                                />
                              </th>
                              <th className="text-left px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.patient')}</th>
                              <th className="text-left px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.phone')}</th>
                              <th className="text-left px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.status')}</th>
                              <th className="text-left px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.outcome')}</th>
                              <th className="text-right px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.attempts')}</th>
                              <th className="w-20 px-3 py-2"></th>
                            </tr>
                          </thead>
                          <tbody className="divide-y">
                            {detail.contacts.map((contact) => {
                              const StatusIcon = CONTACT_STATUS_ICONS[contact.status] || Clock;
                              const isSelected = selectedIds.has(contact.id);
                              return (
                                <tr key={contact.id} className={`hover:bg-muted/30 ${isSelected ? 'bg-primary/5' : ''}`}>
                                  <td className="px-3 py-2">
                                    <Checkbox
                                      checked={isSelected}
                                      onCheckedChange={() => toggleSelect(contact.id)}
                                      aria-label={`Select ${patientNames[contact.patientId] || contact.patientId}`}
                                    />
                                  </td>
                                  <td className="px-3 py-2 text-sm">
                                    {patientNames[contact.patientId] || (
                                      <span className="font-mono text-xs text-muted-foreground">{contact.patientId}</span>
                                    )}
                                  </td>
                                  <td className="px-3 py-2 text-muted-foreground">
                                    {(contact.callContext?.patient_phone as string) || (contact.callContext?.patientPhone as string) || contact.phoneNumber || '—'}
                                  </td>
                                  <td className="px-3 py-2">
                                    <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium ${CONTACT_STATUS_STYLE[contact.status] || 'bg-gray-100 text-gray-600'}`}>
                                      <StatusIcon className="h-3 w-3" />
                                      {formatLabel(contact.status)}
                                    </span>
                                  </td>
                                  <td className="px-3 py-2">
                                    {contact.outcome ? (
                                      <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${OUTCOME_STYLE[contact.outcome] || 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400'}`}>
                                        {formatLabel(contact.outcome)}
                                      </span>
                                    ) : (
                                      <span className="text-xs text-muted-foreground">—</span>
                                    )}
                                  </td>
                                  <td className="px-3 py-2 text-right">{contact.attempts}</td>
                                  <td className="px-3 py-1.5">
                                    <div className="flex items-center gap-1 justify-end">
                                      <button
                                        type="button"
                                        title={t('outbound.contactActions.remove')}
                                        onClick={() => handleContactAction('remove', [contact.id])}
                                        disabled={contactActionPending}
                                        className="p-1 rounded hover:bg-red-100 dark:hover:bg-red-900/30 text-muted-foreground hover:text-red-600 transition-colors"
                                      >
                                        <Trash2 className="h-3.5 w-3.5" />
                                      </button>
                                      <button
                                        type="button"
                                        title={t('outbound.contactActions.addToDnc')}
                                        onClick={() => handleContactAction('add_to_dnc', [contact.id])}
                                        disabled={contactActionPending}
                                        className="p-1 rounded hover:bg-amber-100 dark:hover:bg-amber-900/30 text-muted-foreground hover:text-amber-600 transition-colors"
                                      >
                                        <ShieldBan className="h-3.5 w-3.5" />
                                      </button>
                                    </div>
                                  </td>
                                </tr>
                              );
                            })}
                          </tbody>
                        </table>
                      </div>

                      {cPag && cPag.totalPages > 1 && (
                        <div className="flex items-center justify-between px-3 py-2 border-t bg-muted/30">
                          <div className="text-xs text-muted-foreground">
                            Page {cPag.page} of {cPag.totalPages} ({cPag.total} contacts)
                          </div>
                          <div className="flex items-center gap-1">
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-7 px-2 text-xs"
                              disabled={contactPage <= 1 || loadingDetail}
                              onClick={() => handleContactPageChange(contactPage - 1)}
                            >
                              <ChevronLeft className="h-3.5 w-3.5" />
                              Prev
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-7 px-2 text-xs"
                              disabled={contactPage >= cPag.totalPages || loadingDetail}
                              onClick={() => handleContactPageChange(contactPage + 1)}
                            >
                              Next
                              <ChevronRight className="h-3.5 w-3.5" />
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </>
            ) : null}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
