'use client';

import { useState, useTransition, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { useRouter } from 'next/navigation';
import { Card, CardContent } from '@kit/ui/card';
import { Badge } from '@kit/ui/badge';
import { Button } from '@kit/ui/button';
import { Checkbox } from '@kit/ui/checkbox';
import { toast } from '@kit/ui/sonner';
import { useCsrfToken } from '@kit/shared/hooks/use-csrf-token';
import {
  PhoneOutgoing, MessageSquare, Mail, ChevronDown, ChevronUp,
  Pause, Play, XCircle, Users, CheckCircle2, Clock, Phone,
  AlertCircle, Loader2, Trash2, ShieldBan,
} from 'lucide-react';

const CHANNEL_ICONS: Record<string, typeof PhoneOutgoing> = {
  PHONE: PhoneOutgoing,
  SMS: MessageSquare,
  EMAIL: Mail,
};

interface CampaignContact {
  id: string;
  patientId: string;
  phoneNumber: string | null;
  status: string;
  outcome: string | null;
  attempts: number;
  lastAttemptAt: string | null;
}

interface CampaignDetail {
  contacts: CampaignContact[];
  statusBreakdown: Record<string, number>;
  outcomeBreakdown: Record<string, number>;
}

interface Campaign {
  id: string;
  name: string;
  callType: string;
  channel: string;
  status: string;
  totalContacts: number;
  completedCount: number;
  successfulCount: number;
  isAutoGenerated: boolean;
  createdAt: string;
}

interface CampaignCardProps {
  campaign: Campaign;
  callTypeLabel: string;
  channelLabel: string;
}

const STATUS_COLORS: Record<string, string> = {
  ACTIVE: 'bg-green-600',
  PAUSED: 'bg-amber-500',
  COMPLETED: 'bg-blue-600',
  DRAFT: 'bg-gray-500',
  SCHEDULED: 'bg-purple-600',
  CANCELLED: 'bg-red-500',
};

const CONTACT_STATUS_ICONS: Record<string, typeof CheckCircle2> = {
  COMPLETED: CheckCircle2,
  IN_PROGRESS: Phone,
  QUEUED: Clock,
  FAILED: AlertCircle,
  SKIPPED: XCircle,
};

export function CampaignCard({ campaign, callTypeLabel, channelLabel }: CampaignCardProps) {
  const { t } = useTranslation('common');
  const csrfToken = useCsrfToken();
  const router = useRouter();
  const [expanded, setExpanded] = useState(false);
  const [detail, setDetail] = useState<CampaignDetail | null>(null);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [isPending, startTransition] = useTransition();
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [contactActionPending, setContactActionPending] = useState(false);
  const [patientNames, setPatientNames] = useState<Record<string, string>>({});

  const ChannelIcon = CHANNEL_ICONS[campaign.channel] || PhoneOutgoing;
  const progress = campaign.totalContacts > 0
    ? Math.round((campaign.completedCount / campaign.totalContacts) * 100)
    : 0;

  const canPause = campaign.status === 'ACTIVE';
  const canResume = campaign.status === 'PAUSED';
  const canCancel = ['ACTIVE', 'PAUSED', 'SCHEDULED', 'DRAFT'].includes(campaign.status);

  async function fetchDetail() {
    if (detail) return;
    setLoadingDetail(true);
    try {
      const res = await fetch(`/api/outbound/campaigns/${campaign.id}`);
      if (!res.ok) throw new Error('Failed to fetch');
      const data = await res.json();
      setDetail(data);

      const ids = (data.contacts || []).map((c: any) => c.patientId).filter(Boolean);
      if (ids.length > 0) {
        fetch('/api/outbound/patients/resolve', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ patientIds: ids }),
        })
          .then((r) => (r.ok ? r.json() : null))
          .then((d) => { if (d?.names) setPatientNames(d.names); })
          .catch(() => {});
      }
    } catch {
      toast.error('Failed to load campaign details');
    } finally {
      setLoadingDetail(false);
    }
  }

  function handleToggleExpand() {
    const next = !expanded;
    setExpanded(next);
    if (next) fetchDetail();
    if (!next) setSelectedIds(new Set());
  }

  function handleAction(action: 'pause' | 'resume' | 'cancel') {
    startTransition(async () => {
      try {
        const res = await fetch(`/api/outbound/campaigns/${campaign.id}`, {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'x-csrf-token': csrfToken,
          },
          credentials: 'include',
          body: JSON.stringify({ action }),
        });

        if (!res.ok) {
          const data = await res.json().catch(() => ({}));
          throw new Error(data.error || `Failed to ${action}`);
        }

        const labels: Record<string, string> = {
          pause: t('outbound.campaignActions.paused'),
          resume: t('outbound.campaignActions.resumed'),
          cancel: t('outbound.campaignActions.cancelled'),
        };
        toast.success(labels[action] ?? 'Done');
        setDetail(null);
        router.refresh();
      } catch (err) {
        toast.error(err instanceof Error ? err.message : `Failed to ${action} campaign`);
      }
    });
  }

  const toggleSelect = useCallback((id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const toggleSelectAll = useCallback(() => {
    if (!detail) return;
    setSelectedIds((prev) => {
      if (prev.size === detail.contacts.length) return new Set();
      return new Set(detail.contacts.map((c) => c.id));
    });
  }, [detail]);

  async function handleContactAction(action: 'remove' | 'add_to_dnc', ids?: string[]) {
    const targetIds = ids ?? Array.from(selectedIds);
    if (targetIds.length === 0) return;
    setContactActionPending(true);
    try {
      const res = await fetch(`/api/outbound/campaigns/${campaign.id}/contacts`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-csrf-token': csrfToken,
        },
        credentials: 'include',
        body: JSON.stringify({ action, contactIds: targetIds }),
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Failed');
      }

      const result = await res.json();
      if (action === 'remove') {
        toast.success(t('outbound.contactActions.removed', { count: result.removed }));
      } else {
        toast.success(t('outbound.contactActions.addedToDnc', { count: result.dncAdded }));
      }

      setSelectedIds(new Set());
      setDetail(null);
      await fetchDetail();
      router.refresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed');
    } finally {
      setContactActionPending(false);
    }
  }

  const statusColor = STATUS_COLORS[campaign.status] || 'bg-gray-500';
  const allSelected = detail ? selectedIds.size === detail.contacts.length && detail.contacts.length > 0 : false;
  const someSelected = selectedIds.size > 0;

  return (
    <Card className={expanded ? 'ring-1 ring-primary/20' : 'hover:shadow-sm transition-shadow'}>
      <CardContent className="pt-4 pb-4">
        <button
          type="button"
          className="flex items-center justify-between w-full text-left"
          onClick={handleToggleExpand}
        >
          <div className="flex items-center gap-3">
            <div className="rounded-full bg-muted p-2">
              <ChannelIcon className="h-4 w-4 text-muted-foreground" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <p className="font-medium text-sm">{campaign.name}</p>
                {campaign.isAutoGenerated && (
                  <Badge variant="outline" className="text-xs">
                    {t('outbound.campaign.auto')}
                  </Badge>
                )}
              </div>
              <p className="text-xs text-muted-foreground">
                {callTypeLabel} &middot; {channelLabel}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-right text-sm">
              <p className="font-medium">{campaign.completedCount}/{campaign.totalContacts}</p>
              <p className="text-xs text-muted-foreground">
                {t('outbound.campaign.percentComplete', { percent: progress })}
              </p>
            </div>
            <div className="w-24">
              <div className="h-2 bg-muted rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full transition-all ${statusColor}`}
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>
            <Badge
              variant={
                campaign.status === 'ACTIVE' ? 'default'
                  : campaign.status === 'COMPLETED' ? 'secondary'
                  : 'outline'
              }
              className={campaign.status === 'ACTIVE' ? 'bg-green-600' : campaign.status === 'PAUSED' ? 'bg-amber-500 text-white border-amber-500' : ''}
            >
              {t(`outbound.campaign.status.${campaign.status.toLowerCase()}`)}
            </Badge>
            {expanded ? (
              <ChevronUp className="h-4 w-4 text-muted-foreground" />
            ) : (
              <ChevronDown className="h-4 w-4 text-muted-foreground" />
            )}
          </div>
        </button>

        {expanded && (
          <div className="mt-4 border-t pt-4 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                {canPause && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleAction('pause')}
                    disabled={isPending}
                    className="text-amber-600 border-amber-300 hover:bg-amber-50 dark:hover:bg-amber-950/20"
                  >
                    <Pause className="h-3.5 w-3.5 mr-1.5" />
                    {t('outbound.campaignActions.pause')}
                  </Button>
                )}
                {canResume && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleAction('resume')}
                    disabled={isPending}
                    className="text-green-600 border-green-300 hover:bg-green-50 dark:hover:bg-green-950/20"
                  >
                    <Play className="h-3.5 w-3.5 mr-1.5" />
                    {t('outbound.campaignActions.resume')}
                  </Button>
                )}
                {canCancel && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleAction('cancel')}
                    disabled={isPending}
                    className="text-red-600 border-red-300 hover:bg-red-50 dark:hover:bg-red-950/20"
                  >
                    <XCircle className="h-3.5 w-3.5 mr-1.5" />
                    {t('outbound.campaignActions.cancel')}
                  </Button>
                )}
              </div>
              <p className="text-xs text-muted-foreground">
                {t('outbound.campaignActions.created')}: {new Date(campaign.createdAt).toLocaleDateString()}
              </p>
            </div>

            {loadingDetail ? (
              <div className="flex items-center justify-center py-6">
                <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
              </div>
            ) : detail ? (
              <>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  <div className="rounded-lg bg-muted/50 p-3 text-center">
                    <Users className="h-4 w-4 mx-auto mb-1 text-muted-foreground" />
                    <p className="text-lg font-semibold">{campaign.totalContacts}</p>
                    <p className="text-xs text-muted-foreground">{t('outbound.campaign.contacts')}</p>
                  </div>
                  <div className="rounded-lg bg-muted/50 p-3 text-center">
                    <CheckCircle2 className="h-4 w-4 mx-auto mb-1 text-green-600" />
                    <p className="text-lg font-semibold">{campaign.completedCount}</p>
                    <p className="text-xs text-muted-foreground">{t('outbound.campaign.completed')}</p>
                  </div>
                  <div className="rounded-lg bg-muted/50 p-3 text-center">
                    <CheckCircle2 className="h-4 w-4 mx-auto mb-1 text-blue-600" />
                    <p className="text-lg font-semibold">{campaign.successfulCount}</p>
                    <p className="text-xs text-muted-foreground">{t('outbound.campaign.successful')}</p>
                  </div>
                  <div className="rounded-lg bg-muted/50 p-3 text-center">
                    <Clock className="h-4 w-4 mx-auto mb-1 text-amber-600" />
                    <p className="text-lg font-semibold">
                      {campaign.totalContacts - campaign.completedCount}
                    </p>
                    <p className="text-xs text-muted-foreground">{t('outbound.campaignActions.remaining')}</p>
                  </div>
                </div>

                {Object.keys(detail.outcomeBreakdown).length > 0 && (
                  <div>
                    <p className="text-sm font-medium mb-2">{t('outbound.campaignActions.outcomes')}</p>
                    <div className="flex flex-wrap gap-2">
                      {Object.entries(detail.outcomeBreakdown).map(([outcome, count]) => (
                        <Badge key={outcome} variant="secondary" className="text-xs">
                          {outcome}: {count}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}

                {detail.contacts.length > 0 && (
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <p className="text-sm font-medium">
                        {t('outbound.campaignActions.recentContacts')} ({detail.contacts.length})
                      </p>
                      {someSelected && (
                        <div className="flex items-center gap-2">
                          <span className="text-xs text-muted-foreground">
                            {t('outbound.contactActions.selected', { count: selectedIds.size })}
                          </span>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleContactAction('remove')}
                            disabled={contactActionPending}
                            className="h-7 text-xs text-red-600 border-red-300 hover:bg-red-50 dark:hover:bg-red-950/20"
                          >
                            {contactActionPending ? (
                              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                            ) : (
                              <Trash2 className="h-3 w-3 mr-1" />
                            )}
                            {t('outbound.contactActions.remove')}
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleContactAction('add_to_dnc')}
                            disabled={contactActionPending}
                            className="h-7 text-xs text-amber-600 border-amber-300 hover:bg-amber-50 dark:hover:bg-amber-950/20"
                          >
                            {contactActionPending ? (
                              <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                            ) : (
                              <ShieldBan className="h-3 w-3 mr-1" />
                            )}
                            {t('outbound.contactActions.addToDnc')}
                          </Button>
                        </div>
                      )}
                    </div>
                    <div className="border rounded-lg overflow-hidden">
                      <div className="max-h-60 overflow-y-auto">
                        <table className="w-full text-sm">
                          <thead className="bg-muted/50 sticky top-0">
                            <tr>
                              <th className="w-10 px-3 py-2">
                                <Checkbox
                                  checked={allSelected}
                                  onCheckedChange={toggleSelectAll}
                                  aria-label="Select all"
                                />
                              </th>
                              <th className="text-left px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.patient')}</th>
                              <th className="text-left px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.phone')}</th>
                              <th className="text-left px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.status')}</th>
                              <th className="text-left px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.outcome')}</th>
                              <th className="text-right px-3 py-2 font-medium text-xs">{t('outbound.campaignActions.attempts')}</th>
                              <th className="w-20 px-3 py-2"></th>
                            </tr>
                          </thead>
                          <tbody className="divide-y">
                            {detail.contacts.map((contact) => {
                              const StatusIcon = CONTACT_STATUS_ICONS[contact.status] || Clock;
                              const isSelected = selectedIds.has(contact.id);
                              return (
                                <tr key={contact.id} className={`hover:bg-muted/30 ${isSelected ? 'bg-primary/5' : ''}`}>
                                  <td className="px-3 py-2">
                                    <Checkbox
                                      checked={isSelected}
                                      onCheckedChange={() => toggleSelect(contact.id)}
                                      aria-label={`Select ${patientNames[contact.patientId] || contact.patientId}`}
                                    />
                                  </td>
                                  <td className="px-3 py-2 text-sm">
                                    {patientNames[contact.patientId] || (
                                      <span className="font-mono text-xs text-muted-foreground">{contact.patientId}</span>
                                    )}
                                  </td>
                                  <td className="px-3 py-2 text-muted-foreground">{contact.phoneNumber || '—'}</td>
                                  <td className="px-3 py-2">
                                    <div className="flex items-center gap-1.5">
                                      <StatusIcon className="h-3.5 w-3.5 text-muted-foreground" />
                                      <span className="text-xs">{contact.status}</span>
                                    </div>
                                  </td>
                                  <td className="px-3 py-2 text-xs">{contact.outcome || '—'}</td>
                                  <td className="px-3 py-2 text-right">{contact.attempts}</td>
                                  <td className="px-3 py-1.5">
                                    <div className="flex items-center gap-1 justify-end">
                                      <button
                                        type="button"
                                        title={t('outbound.contactActions.remove')}
                                        onClick={() => handleContactAction('remove', [contact.id])}
                                        disabled={contactActionPending}
                                        className="p-1 rounded hover:bg-red-100 dark:hover:bg-red-900/30 text-muted-foreground hover:text-red-600 transition-colors"
                                      >
                                        <Trash2 className="h-3.5 w-3.5" />
                                      </button>
                                      <button
                                        type="button"
                                        title={t('outbound.contactActions.addToDnc')}
                                        onClick={() => handleContactAction('add_to_dnc', [contact.id])}
                                        disabled={contactActionPending}
                                        className="p-1 rounded hover:bg-amber-100 dark:hover:bg-amber-900/30 text-muted-foreground hover:text-amber-600 transition-colors"
                                      >
                                        <ShieldBan className="h-3.5 w-3.5" />
                                      </button>
                                    </div>
                                  </td>
                                </tr>
                              );
                            })}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                )}
              </>
            ) : null}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
