import {
  Controller,
  Get,
  Post,
  Patch,
  Delete,
  Body,
  Param,
  Query,
  HttpException,
  HttpStatus,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { OutboundCampaignService } from './services/outbound-campaign.service';
import { OutboundSettingsService } from './services/outbound-settings.service';
import { OutboundSchedulerService } from './services/outbound-scheduler.service';
import { OutboundDispatcherService } from './services/outbound-dispatcher.service';
import { StructuredLogger } from '../common/structured-logger';
import type { OutboundCallType, OutboundChannel, OutboundCampaignStatus } from '@kit/prisma';

const CALL_TYPE_MAP: Record<string, OutboundCallType> = {
  recall: 'RECALL',
  reminder: 'REMINDER',
  followup: 'FOLLOWUP',
  noshow: 'NOSHOW',
  treatment_plan: 'TREATMENT_PLAN',
  postop: 'POSTOP',
  reactivation: 'REACTIVATION',
  survey: 'SURVEY',
  welcome: 'WELCOME',
  payment: 'PAYMENT',
  benefits: 'BENEFITS',
};

function normalizeCallType(raw: string): OutboundCallType {
  return CALL_TYPE_MAP[raw.toLowerCase()] || (raw as OutboundCallType);
}

@Controller('outbound')
export class OutboundController {
  private readonly logger = new StructuredLogger(OutboundController.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly campaignService: OutboundCampaignService,
    private readonly settingsService: OutboundSettingsService,
    private readonly schedulerService: OutboundSchedulerService,
    private readonly dispatcherService: OutboundDispatcherService,
  ) {}

  // ── Settings ────────────────────────────────────────────────────────────

  @Get('settings/:accountId')
  async getSettings(@Param('accountId') accountId: string) {
    return this.settingsService.getOrCreateSettings(accountId);
  }

  @Patch('settings/:accountId')
  async updateSettings(
    @Param('accountId') accountId: string,
    @Body() body: Record<string, unknown>,
  ) {
    return this.settingsService.updateSettings(accountId, body as any);
  }

  @Post('settings/:accountId/enable')
  async enableAgentGroup(
    @Param('accountId') accountId: string,
    @Body() body: { group: 'PATIENT_CARE' | 'FINANCIAL' },
  ) {
    if (!body.group || !['PATIENT_CARE', 'FINANCIAL'].includes(body.group)) {
      throw new HttpException(
        'Invalid group. Must be PATIENT_CARE or FINANCIAL.',
        HttpStatus.BAD_REQUEST,
      );
    }
    const result = await this.settingsService.enableAgentGroup(accountId, body.group);

    this.schedulerService
      .bootstrapCampaignsForAccount(accountId, body.group)
      .catch((err) =>
        this.logger.error({
          accountId,
          group: body.group,
          err: err instanceof Error ? err.message : err,
          msg: 'Auto-bootstrap failed (non-blocking)',
        }),
      );

    return result;
  }

  @Post('settings/:accountId/disable')
  async disableAgentGroup(
    @Param('accountId') accountId: string,
    @Body() body: { group: 'PATIENT_CARE' | 'FINANCIAL' },
  ) {
    if (!body.group || !['PATIENT_CARE', 'FINANCIAL'].includes(body.group)) {
      throw new HttpException(
        'Invalid group. Must be PATIENT_CARE or FINANCIAL.',
        HttpStatus.BAD_REQUEST,
      );
    }
    return this.settingsService.disableAgentGroup(accountId, body.group);
  }

  // ── Campaigns ───────────────────────────────────────────────────────────

  @Get('campaigns/:accountId')
  async listCampaigns(
    @Param('accountId') accountId: string,
    @Query('status') status?: OutboundCampaignStatus,
    @Query('callType') callType?: OutboundCallType,
    @Query('isAutoGenerated') isAutoGenerated?: string,
  ) {
    return this.campaignService.listCampaigns(accountId, {
      status,
      callType,
      isAutoGenerated: isAutoGenerated === 'true' ? true : isAutoGenerated === 'false' ? false : undefined,
    });
  }

  @Get('campaigns/:accountId/:campaignId')
  async getCampaign(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return campaign;
  }

  @Post('campaigns/:accountId')
  async createCampaign(
    @Param('accountId') accountId: string,
    @Body()
    body: {
      name: string;
      callType: OutboundCallType;
      channel?: OutboundChannel;
      scheduledStartAt?: string;
      callingWindowStart?: string;
      callingWindowEnd?: string;
      timezone?: string;
      maxConcurrent?: number;
      maxAttemptsPerContact?: number;
      createdBy?: string;
    },
  ) {
    return this.campaignService.createCampaign({
      accountId,
      name: body.name,
      callType: body.callType,
      channel: body.channel,
      scheduledStartAt: body.scheduledStartAt
        ? new Date(body.scheduledStartAt)
        : undefined,
      callingWindowStart: body.callingWindowStart,
      callingWindowEnd: body.callingWindowEnd,
      timezone: body.timezone,
      maxConcurrent: body.maxConcurrent,
      maxAttemptsPerContact: body.maxAttemptsPerContact,
      createdBy: body.createdBy,
    });
  }

  @Patch('campaigns/:accountId/:campaignId/status')
  async updateCampaignStatus(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
    @Body() body: { status: OutboundCampaignStatus },
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return this.campaignService.updateCampaignStatus(campaignId, body.status);
  }

  @Post('campaigns/:accountId/:campaignId/contacts')
  async addContacts(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
    @Body()
    body: {
      contacts: Array<{
        patientId: string;
        phoneNumber?: string;
        callContext?: Record<string, unknown>;
      }>;
    },
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return this.campaignService.addContacts(campaignId, body.contacts);
  }

  @Get('campaigns/:accountId/:campaignId/contacts')
  async getContacts(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
    @Query('status') status?: string,
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return this.campaignService.getContacts(campaignId, { status });
  }

  // ── Campaign Approval ──────────────────────────────────────────────────

  @Patch('campaigns/:accountId/:campaignId/approve')
  async approveCampaign(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return this.campaignService.approveCampaign(campaignId);
  }

  @Post('campaigns/:accountId/approve-all')
  async approveAllDraftCampaigns(
    @Param('accountId') accountId: string,
  ) {
    return this.campaignService.approveAllDraftCampaigns(accountId);
  }

  // ── Admin: Manual Scan Trigger ────────────────────────────────────────

  @Post('admin/trigger-scan')
  async triggerScan(
    @Body()
    body: {
      scanTypes: Array<'recall' | 'reminder' | 'noshow' | 'reactivation' | 'all'>;
      accountIds?: string[];
    },
  ) {
    const { scanTypes, accountIds: rawAccountIds } = body;

    if (!scanTypes?.length) {
      throw new HttpException(
        'scanTypes is required',
        HttpStatus.BAD_REQUEST,
      );
    }

    const accountIds = (rawAccountIds || []).filter(
      (id: unknown): id is string => typeof id === 'string' && id.length > 0,
    );

    let accounts: Array<{ id: string; settings: any }>;

    if (accountIds.length) {
      const settingsList = await this.prisma.outboundSettings.findMany({
        where: { accountId: { in: accountIds } },
      });
      accounts = settingsList.map((s) => ({ id: s.accountId, settings: s }));
    } else {
      const settingsList = await this.prisma.outboundSettings.findMany({
        where: {
          OR: [
            { patientCareEnabled: true },
            { financialEnabled: true },
          ],
        },
      });
      accounts = settingsList.map((s) => ({ id: s.accountId, settings: s }));
    }

    const results: Array<{
      accountId: string;
      scansRun: string[];
      error?: string;
    }> = [];

    for (const acct of accounts) {
      try {
        const scansRun = await this.schedulerService.triggerScansForAccount(
          acct.id,
          acct.settings,
          scanTypes,
        );
        results.push({ accountId: acct.id, scansRun });
      } catch (err) {
        this.logger.error({
          accountId: acct.id,
          err: err instanceof Error ? err.message : err,
          msg: '[Admin] Manual scan trigger failed',
        });
        results.push({
          accountId: acct.id,
          scansRun: [],
          error: err instanceof Error ? err.message : 'Unknown error',
        });
      }
    }

    return {
      success: true,
      totalAccounts: accounts.length,
      results,
    };
  }

  // ── Admin: Test Run ─────────────────────────────────────────────────────

  @Post('admin/test-run')
  async testRun(
    @Body()
    body: {
      accountId: string;
      callType: OutboundCallType;
      phoneNumbers: string[];
    },
  ) {
    const { accountId, phoneNumbers } = body;
    const callType = normalizeCallType(body.callType as string);

    if (!accountId || !body.callType || !phoneNumbers?.length) {
      throw new HttpException(
        'accountId, callType, and phoneNumbers are required',
        HttpStatus.BAD_REQUEST,
      );
    }

    const settings = await this.settingsService.getSettings(accountId);
    if (!settings) {
      throw new HttpException(
        'No outbound settings found for this account',
        HttpStatus.NOT_FOUND,
      );
    }

    const campaign = await this.campaignService.createCampaign({
      accountId,
      name: `Admin Test Run - ${new Date().toISOString().slice(0, 16)}`,
      callType,
      channel: 'PHONE',
      isAutoGenerated: false,
      maxConcurrent: phoneNumbers.length,
      timezone: settings.timezone || 'America/New_York',
    });

    await this.campaignService.updateCampaignStatus(campaign.id, 'ACTIVE');

    const contacts = phoneNumbers.map((phone, i) => ({
      patientId: `test-${i}`,
      phoneNumber: phone.startsWith('+') ? phone : `+${phone}`,
      callContext: { patient_name: `Test Contact ${i + 1}` },
    }));

    const { added } = await this.campaignService.addContacts(campaign.id, contacts);

    this.logger.log({
      campaignId: campaign.id,
      accountId,
      callType,
      contactCount: added,
      msg: '[Admin] Test run campaign created, dispatching immediately',
    });

    this.dispatcherService.processTestCampaign(campaign.id).catch((err) => {
      this.logger.error({
        campaignId: campaign.id,
        err: err instanceof Error ? err.message : err,
        msg: '[Admin] Test run dispatch failed',
      });
    });

    return {
      success: true,
      campaignId: campaign.id,
      accountId,
      callType,
      contactsAdded: added,
    };
  }

  @Post('admin/test-run/:campaignId/abort')
  async abortTestRun(@Param('campaignId') campaignId: string) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }

    await this.campaignService.updateCampaignStatus(campaignId, 'CANCELLED');

    const { count } = await this.prisma.campaignContact.updateMany({
      where: {
        campaignId,
        status: 'QUEUED',
      },
      data: {
        status: 'CANCELLED',
        outcome: 'admin_aborted',
        completedAt: new Date(),
      },
    });

    this.logger.log({
      campaignId,
      cancelledContacts: count,
      msg: '[Admin] Test run aborted',
    });

    return {
      success: true,
      campaignId,
      cancelledContacts: count,
    };
  }

  // ── Admin: Delete Campaign ──────────────────────────────────────────────

  @Delete('admin/campaigns/:campaignId')
  async deleteCampaign(@Param('campaignId') campaignId: string) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }

    const activeStatuses = ['ACTIVE', 'SCHEDULED'];
    if (activeStatuses.includes(campaign.status)) {
      throw new HttpException(
        'Cannot delete an active or scheduled campaign. Cancel it first.',
        HttpStatus.BAD_REQUEST,
      );
    }

    await this.prisma.outboundCampaign.delete({
      where: { id: campaignId },
    });

    this.logger.log({
      campaignId,
      accountId: campaign.accountId,
      msg: '[Admin] Campaign deleted',
    });

    return { success: true, campaignId };
  }

  // ── Do Not Call ─────────────────────────────────────────────────────────

  @Get('dnc/:accountId')
  async getDncList(@Param('accountId') accountId: string) {
    return this.prisma.doNotCallEntry.findMany({
      where: { accountId },
      orderBy: { createdAt: 'desc' },
    });
  }

  @Post('dnc/:accountId')
  async addToDnc(
    @Param('accountId') accountId: string,
    @Body() body: { phoneNumber: string; reason?: string },
  ) {
    return this.prisma.doNotCallEntry.upsert({
      where: {
        accountId_phoneNumber: {
          accountId,
          phoneNumber: body.phoneNumber,
        },
      },
      update: { reason: body.reason || 'manual' },
      create: {
        accountId,
        phoneNumber: body.phoneNumber,
        reason: body.reason || 'patient_requested',
        source: 'manual',
      },
    });
  }

}
