import {
  Controller,
  Get,
  Post,
  Patch,
  Body,
  Param,
  Query,
  HttpException,
  HttpStatus,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { OutboundCampaignService } from './services/outbound-campaign.service';
import { OutboundSettingsService } from './services/outbound-settings.service';
import { OutboundSchedulerService } from './services/outbound-scheduler.service';
import { StructuredLogger } from '../common/structured-logger';
import type { OutboundCallType, OutboundChannel, OutboundCampaignStatus } from '@kit/prisma';

@Controller('outbound')
export class OutboundController {
  private readonly logger = new StructuredLogger(OutboundController.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly campaignService: OutboundCampaignService,
    private readonly settingsService: OutboundSettingsService,
    private readonly schedulerService: OutboundSchedulerService,
  ) {}

  // ── Settings ────────────────────────────────────────────────────────────

  @Get('settings/:accountId')
  async getSettings(@Param('accountId') accountId: string) {
    return this.settingsService.getOrCreateSettings(accountId);
  }

  @Patch('settings/:accountId')
  async updateSettings(
    @Param('accountId') accountId: string,
    @Body() body: Record<string, unknown>,
  ) {
    return this.settingsService.updateSettings(accountId, body as any);
  }

  @Post('settings/:accountId/enable')
  async enableAgentGroup(
    @Param('accountId') accountId: string,
    @Body() body: { group: 'PATIENT_CARE' | 'FINANCIAL' },
  ) {
    if (!body.group || !['PATIENT_CARE', 'FINANCIAL'].includes(body.group)) {
      throw new HttpException(
        'Invalid group. Must be PATIENT_CARE or FINANCIAL.',
        HttpStatus.BAD_REQUEST,
      );
    }
    const result = await this.settingsService.enableAgentGroup(accountId, body.group);

    this.schedulerService
      .bootstrapCampaignsForAccount(accountId, body.group)
      .catch((err) =>
        this.logger.error({
          accountId,
          group: body.group,
          err: err instanceof Error ? err.message : err,
          msg: 'Auto-bootstrap failed (non-blocking)',
        }),
      );

    return result;
  }

  @Post('settings/:accountId/disable')
  async disableAgentGroup(
    @Param('accountId') accountId: string,
    @Body() body: { group: 'PATIENT_CARE' | 'FINANCIAL' },
  ) {
    if (!body.group || !['PATIENT_CARE', 'FINANCIAL'].includes(body.group)) {
      throw new HttpException(
        'Invalid group. Must be PATIENT_CARE or FINANCIAL.',
        HttpStatus.BAD_REQUEST,
      );
    }
    return this.settingsService.disableAgentGroup(accountId, body.group);
  }

  // ── Campaigns ───────────────────────────────────────────────────────────

  @Get('campaigns/:accountId')
  async listCampaigns(
    @Param('accountId') accountId: string,
    @Query('status') status?: OutboundCampaignStatus,
    @Query('callType') callType?: OutboundCallType,
    @Query('isAutoGenerated') isAutoGenerated?: string,
  ) {
    return this.campaignService.listCampaigns(accountId, {
      status,
      callType,
      isAutoGenerated: isAutoGenerated === 'true' ? true : isAutoGenerated === 'false' ? false : undefined,
    });
  }

  @Get('campaigns/:accountId/:campaignId')
  async getCampaign(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return campaign;
  }

  @Post('campaigns/:accountId')
  async createCampaign(
    @Param('accountId') accountId: string,
    @Body()
    body: {
      name: string;
      callType: OutboundCallType;
      channel?: OutboundChannel;
      scheduledStartAt?: string;
      callingWindowStart?: string;
      callingWindowEnd?: string;
      timezone?: string;
      maxConcurrent?: number;
      maxAttemptsPerContact?: number;
      createdBy?: string;
    },
  ) {
    return this.campaignService.createCampaign({
      accountId,
      name: body.name,
      callType: body.callType,
      channel: body.channel,
      scheduledStartAt: body.scheduledStartAt
        ? new Date(body.scheduledStartAt)
        : undefined,
      callingWindowStart: body.callingWindowStart,
      callingWindowEnd: body.callingWindowEnd,
      timezone: body.timezone,
      maxConcurrent: body.maxConcurrent,
      maxAttemptsPerContact: body.maxAttemptsPerContact,
      createdBy: body.createdBy,
    });
  }

  @Patch('campaigns/:accountId/:campaignId/status')
  async updateCampaignStatus(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
    @Body() body: { status: OutboundCampaignStatus },
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return this.campaignService.updateCampaignStatus(campaignId, body.status);
  }

  @Post('campaigns/:accountId/:campaignId/contacts')
  async addContacts(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
    @Body()
    body: {
      contacts: Array<{
        patientId?: string;
        patientName: string;
        phoneNumber: string;
        email?: string;
        callContext?: Record<string, unknown>;
      }>;
    },
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return this.campaignService.addContacts(campaignId, body.contacts);
  }

  @Get('campaigns/:accountId/:campaignId/contacts')
  async getContacts(
    @Param('accountId') accountId: string,
    @Param('campaignId') campaignId: string,
    @Query('status') status?: string,
  ) {
    const campaign = await this.campaignService.getCampaign(campaignId);
    if (!campaign || campaign.accountId !== accountId) {
      throw new HttpException('Campaign not found', HttpStatus.NOT_FOUND);
    }
    return this.campaignService.getContacts(campaignId, { status });
  }

  // ── Do Not Call ─────────────────────────────────────────────────────────

  @Get('dnc/:accountId')
  async getDncList(@Param('accountId') accountId: string) {
    return this.prisma.doNotCallEntry.findMany({
      where: { accountId },
      orderBy: { createdAt: 'desc' },
    });
  }

  @Post('dnc/:accountId')
  async addToDnc(
    @Param('accountId') accountId: string,
    @Body() body: { phoneNumber: string; reason?: string },
  ) {
    return this.prisma.doNotCallEntry.upsert({
      where: {
        accountId_phoneNumber: {
          accountId,
          phoneNumber: body.phoneNumber,
        },
      },
      update: { reason: body.reason || 'manual' },
      create: {
        accountId,
        phoneNumber: body.phoneNumber,
        reason: body.reason || 'patient_requested',
        source: 'manual',
      },
    });
  }

}
